// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 앱 runtime용 — Neon Pooler URL
    url: process.env["DATABASE_URL"],
    // 마이그레이션 전용 — Neon Direct URL (없으면 url로 fallback)
    directUrl: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
